"""add_callback_fields_to_research

Revision ID: 11af0049c975
Revises: 
Create Date: 2025-06-28 14:09:04.922433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11af0049c975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researches', sa.Column('callback_enabled', sa.Boolean(), nullable=True))
    op.add_column('researches', sa.Column('callback_url', sa.String(length=500), nullable=True))
    op.add_column('researches', sa.Column('callback_data', sa.JSON(), nullable=True))
    op.add_column('researches', sa.Column('callback_sent', sa.Boolean(), nullable=True))
    op.add_column('researches', sa.Column('callback_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researches', 'callback_sent_at')
    op.drop_column('researches', 'callback_sent')
    op.drop_column('researches', 'callback_data')
    op.drop_column('researches', 'callback_url')
    op.drop_column('researches', 'callback_enabled')
    # ### end Alembic commands ### 