"""remove_query_index_fix_large_text_issue

Revision ID: f075031cda51
Revises: 11af0049c975
Create Date: 2025-06-28 18:04:19.879443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f075031cda51'
down_revision = '11af0049c975'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_researches_query'), table_name='researches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_researches_query'), 'researches', ['query'], unique=False)
    # ### end Alembic commands ### 