from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from datetime import datetime, UTC
from app.database import Base


class Research(Base):
    """Model to track research investigations"""
    __tablename__ = "researches"
    
    id = Column(Integer, primary_key=True, index=True)
    query = Column(Text, nullable=False, index=True)  # Original research question/input
    directory_path = Column(String(500), nullable=False)  # MinIO directory path
    status = Column(String(50), default="pending")  # pending, in_progress, completed, failed
    created_at = Column(DateTime, default=datetime.now(UTC))
    updated_at = Column(DateTime, default=datetime.now(UTC), onupdate=datetime.now(UTC))
    completed_at = Column(DateTime, nullable=True)
    
    # LLM Configuration used
    llm_provider = Column(String(50), default="openai")  # openai, anthropic, google, deepseek
    llm_model = Column(String(100), default="gpt-4o-mini")
    
    # Perplexity Configuration used
    perplexity_model = Column(String(100), default="sonar-pro")  # sonar-pro, sonar-deep-research, etc.
    
    # Relationships
    tasks = relationship("ResearchTask", back_populates="research", cascade="all, delete-orphan")
    similar_researches = relationship(
        "SimilarResearch", 
        foreign_keys="[SimilarResearch.research_id]", 
        back_populates="research", 
        cascade="all, delete-orphan"
    )


class ResearchTask(Base):
    """Model to track individual research tasks within an investigation"""
    __tablename__ = "research_tasks"
    
    id = Column(Integer, primary_key=True, index=True)
    research_id = Column(Integer, ForeignKey("researches.id"), nullable=False)
    task_query = Column(Text, nullable=False)  # Specific task question generated by planner agent
    task_order = Column(Integer, nullable=False)  # Order in the investigation structure
    status = Column(String(50), default="pending")  # pending, completed, failed
    minio_file_path = Column(String(500), nullable=True)  # Path to the .md file in MinIO
    created_at = Column(DateTime, default=datetime.now(UTC))
    completed_at = Column(DateTime, nullable=True)
    
    # Relationships
    research = relationship("Research", back_populates="tasks")


class SimilarResearch(Base):
    """Model to track similar researches found during investigation"""
    __tablename__ = "similar_researches"
    
    id = Column(Integer, primary_key=True, index=True)
    research_id = Column(Integer, ForeignKey("researches.id"), nullable=False)
    similar_research_id = Column(Integer, ForeignKey("researches.id"), nullable=True)  # If similar to existing research
    similarity_description = Column(Text, nullable=True)  # Description of the similarity
    is_sufficient = Column(Boolean, default=False)  # Whether similar research is sufficient
    created_at = Column(DateTime, default=datetime.now(UTC))
    
    # Relationships
    research = relationship("Research", back_populates="similar_researches", foreign_keys=[research_id])
    similar_to = relationship("Research", foreign_keys=[similar_research_id]) 